/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EW978za2xbq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardContent, CardFooter, Card, CardHeader } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

export function PageHome() {
  return (
    (<div key="1" className="flex flex-col min-h-[100dvh]">
      <header className="bg-gray-600   px-4 lg:px-6 h-14 flex items-center">
        <div className="container flex items-center gap-4 px-4  md:px-6 w-full  h-screen">
          <Link className="mr-10 flex items-center justify-center " href="#">
            <MountainIcon className="h-6 w-6" />
            <span className="">Enamórate </span>
          </Link>
          <nav className="hidden lg:flex items-center gap-4 lg:gap-6 ">
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
              New Arrivals
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
              Accessories
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
              Jewelry
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
              Bags
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
              Sale
            </Link>
          </nav>
          <div className="ml-auto flex items-center gap-4 lg:gap-6 " >
            <Link className="rounded-full overflow-hidden" href="#">
              <img
                alt="User"
                className="rounded-full aspect-square object-cover"
                height="32"
                src="/placeholder.svg"
                width="32" />
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
              Sign In
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
              Create Account
            </Link>
            <Button variant="outline">
              <ShoppingCartIcon className="h-5 w-5" />
            </Button>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className=" bg-gray-900 w-full ">
          <div className="container px-4 md:px-6 h-screen ">
            <div className="grid content-around gap-6 lg:grid-cols-2 lg:gap-12 h-screen  ">
              <div className="flex flex-col justify-center space-y-4 ">
                <div className="space-y-2 ">
                  <h1
                    className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    New Season, New Style
                  </h1>
                  <p
                    className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                    Elevate your look with our stunning collection of accessories. From chic sunglasses to elegant
                    scarves, we have everything you need to add a touch of glamour to your outfit.
                  </p>
                </div>
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#">
                  Shop Now
                </Link>
              </div>
              <img
                alt="Banner"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center lg:order-last "
                height="380"
                src="/placeholder.svg"
                width="730" />
            </div >
          </div>
        </section>




        <section className="bg-gray-950 grid content-center w-full py-12 md:py-24 ">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Summer Essentials
                </div>
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                  Elevate Your Style with Chic Accessories
                </h2>
                <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Let your personality shine with our curated collection of stylish accessories. From elegant scarves to
                  statement jewelry, we have everything you need to complete your look.
                </p>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-4">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Stylish Scarves</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Add a pop of color to your outfit with our beautiful scarves.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Statement Jewelry</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Elevate your look with our stunning collection of jewelry.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>


        <section className="bg-gray-900 h-screen w-full py-12 md:py-24">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div
                  className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Featured Collection
                </div>
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                  Enchanting Elegance: Shop the Look
                </h2>
                <p
                  className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Discover the allure of our featured collection. Embrace timeless elegance with our carefully curated
                  pieces that are perfect for any occasion.
                </p>
              </div>
              <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
                <Card>
                  <CardContent className="p-4">
                    <img
                      alt="Image"
                      className="mx-auto aspect-square overflow-hidden rounded-lg object-cover object-center"
                      height="200"
                      src="/placeholder.svg"
                      width="200" />
                    <h3 className="text-lg font-bold">Floral Delight Scarf</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Elegant scarf with a delicate floral pattern.
                    </p>
                  </CardContent>
                  <CardFooter className="border-t">
                    <Button size="sm">View Details</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardContent className="p-4">
                    <img
                      alt="Image"
                      className="mx-auto aspect-square overflow-hidden rounded-lg object-cover object-center"
                      height="200"
                      src="/placeholder.svg"
                      width="200" />
                    <h3 className="text-lg font-bold">Crystal Elegance Earrings</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Stunning earrings featuring sparkling crystals.
                    </p>
                  </CardContent>
                  <CardFooter className="border-t">
                    <Button size="sm">View Details</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardContent className="p-4">
                    <img
                      alt="Image"
                      className="mx-auto aspect-square overflow-hidden rounded-lg object-cover object-center"
                      height="200"
                      src="/placeholder.svg"
                      width="200" />
                    <h3 className="text-lg font-bold">Chic & Stylish Bracelet</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Add a touch of style with this elegant bracelet.
                    </p>
                  </CardContent>
                  <CardFooter className="border-t">
                    <Button size="sm">View Details</Button>
                  </CardFooter>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gray-950 h-screen w-full py-12 md:py-24">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div
                  className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Summer Vibes
                </div>
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                  Embrace the Season: Discover New Arrivals
                </h2>
                <p
                  className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Let your style bloom with our summer collection. From chic sunglasses to beach-ready hats, we have
                  everything you need to make a statement.
                </p>
              </div>
              <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
                <Card>
                  <CardContent className="p-4">
                    <img
                      alt="Image"
                      className="mx-auto aspect-square overflow-hidden rounded-lg object-cover object-center"
                      height="200"
                      src="/placeholder.svg"
                      width="200" />
                    <h3 className="text-lg font-bold">Trendy Sunglasses</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Add a touch of style with these trendy sunglasses.
                    </p>
                  </CardContent>
                  <CardFooter className="border-t">
                    <Button size="sm">View Details</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardContent className="p-4">
                    <img
                      alt="Image"
                      className="mx-auto aspect-square overflow-hidden rounded-lg object-cover object-center"
                      height="200"
                      src="/placeholder.svg"
                      width="200" />
                    <h3 className="text-lg font-bold">Beach-Ready Hat</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Stay cool with this stylish beach-ready hat.
                    </p>
                  </CardContent>
                  <CardFooter className="border-t">
                    <Button size="sm">View Details</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardContent className="p-4">
                    <img
                      alt="Image"
                      className="mx-auto aspect-square overflow-hidden rounded-lg object-cover object-center"
                      height="200"
                      src="/placeholder.svg"
                      width="200" />
                    <h3 className="text-lg font-bold">Summer Tote Bag</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Carry your essentials in style with this summer tote bag.
                    </p>
                  </CardContent>
                  <CardFooter className="border-t">
                    <Button size="sm">View Details</Button>
                  </CardFooter>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section className=" bg-gray-950 w-full py-12 md:py-24">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div
                  className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Summer Sale
                </div>
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                  Hot Deals: Shop the Summer Sale
                </h2>
                <Link
                  className="inline-flex h-9 w-[200px] items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#">
                  Shop All Products
                </Link>
              </div>
              <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
                <Card>
                  <CardHeader className="p-0">
                    <img
                      alt="Image"
                      className="aspect-square overflow-hidden object-cover object-center"
                      height="200"
                      src="/placeholder.svg"
                      width="200" />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-sm font-medium">Floral Delight Scarf</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Elegant scarf with a delicate floral pattern.
                    </p>
                    <div className="mt-2 flex items-center justify-between">
                      <span className="text-sm font-medium">$19.99</span>
                      <Button size="sm">Add to Cart</Button>
                    </div>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="p-0">
                    <img
                      alt="Image"
                      className="aspect-square overflow-hidden object-cover object-center"
                      height="200"
                      src="/placeholder.svg"
                      width="200" />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-sm font-medium">Crystal Elegance Earrings</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Stunning earrings featuring sparkling crystals.
                    </p>
                    <div className="mt-2 flex items-center justify-between">
                      <span className="text-sm font-medium">$24.99</span>
                      <Button size="sm">Add to Cart</Button>
                    </div>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="p-0">
                    <img
                      alt="Image"
                      className="aspect-square overflow-hidden object-cover object-center"
                      height="200"
                      src="/placeholder.svg"
                      width="200" />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-sm font-medium">Chic & Stylish Bracelet</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Add a touch of style with this elegant bracelet.
                    </p>
                    <div className="mt-2 flex items-center justify-between">
                      <span className="text-sm font-medium">$14.99</span>
                      <Button size="sm">Add to Cart</Button>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section className=" bg-gray-950 w-full py-12 md:py-24">
          <div className="container px-4 md:px-6">
            <div className="grid gap-10 sm:px-10 md:gap-16 md:grid-cols-2">
              <div className="space-y-3">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                  Experience the workflow the best frontend teams love.
                </h2>
                <p
                  className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Let your team focus on shipping features instead of managing infrastructure with automated CI/CD.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <form className="flex space-x-2">
                  <Input className="max-w-lg flex-1" placeholder="Enter your email" type="email" />
                  <Button type="submit">Sign Up</Button>
                </form>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  Sign up to get notified when we launch.
                  <Link className="underline underline-offset-2" href="#">
                    Terms & Conditions
                  </Link>
                </p>
              </div>
            </div>
          </div>
        </section>
        
       
       
        
       
      </main>
      
    </div>)
  );
}

function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}


function ShoppingCartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path
        d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>)
  );
}
